apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map
  namespace: dev-release-team-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map
    spec:
      containers:
      - image: quay.io/scoheb/user-workload@sha256:d76412ee40fd6f9b980e9886e70e6ae671ce9430e6453c34309fb0acf9ae7f19
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
